-- Jalankan seluruh SQL ini di Supabase SQL Editor.
-- Authentication > Providers: aktifkan Email.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Pengguna',
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('income','expense')),
  title text not null,
  category text not null default 'Lainnya',
  amount numeric(14,2) not null check (amount > 0),
  transaction_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  amount numeric(14,2) not null check (amount > 0),
  month date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_amount numeric(14,2) not null check (target_amount > 0),
  saved_amount numeric(14,2) not null default 0 check (saved_amount >= 0),
  target_date date,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.transactions enable row level security;
alter table public.budgets enable row level security;
alter table public.wishlists enable row level security;

drop policy if exists "profiles own" on public.profiles;
create policy "profiles own" on public.profiles
for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "transactions own" on public.transactions;
create policy "transactions own" on public.transactions
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "budgets own" on public.budgets;
create policy "budgets own" on public.budgets
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "wishlists own" on public.wishlists;
create policy "wishlists own" on public.wishlists
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Membuat profile otomatis ketika user baru mendaftar.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'Pengguna'));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();